name: Verify

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: "latest"
          java-version: "17"
          components: "native-image"
      - name: Build
        run: |
          mvn -B package
          mvn -B -Pnative -DskipTests native:compile
      - name: Run application
        run: |
          ./target/spring-boot-native-test &
          sleep 30
          killall java
